services:
  - type: web
    name: truck-trip-planner-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: ./render_start.sh
    autoDeploy: true

