# Generated by Django 6.0.4 on 2026-04-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_tripplan_trip_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripplan",
            name="trip_no",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
